version: '3'

services:
  db:
    image: postgres
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8002 ApiDockerBasicCrud.wsgi
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db